# Generated by Django 5.1 on 2024-08-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixels',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='pixels/'),
        ),
    ]
